image: alpine:3.10.2

stages:
  - welcome

before_script:
  - uname -a

hello world CI/CD job:
  stage: welcome
  services:
    - docker:dind
  script:
    - cat /etc/alpine-release
    - echo 'Hello gitlab CI/CD'
